name: dask
channels:
  - defaults
  - conda-forge
  - nvidia 
  - rapidsai 
  - rapidsai/label/xgboost
    
dependencies:
  - python=3.7
  - cudatoolkit
  - cudf 
  - cuml 
  - cugraph
#   - dask-cuda  # Installing from master below
  - dask-cudf
  - rapidsai/label/xgboost::xgboost=0.90.*
  - rapidsai/label/xgboost::dask-xgboost=0.2.*
  - dill
  - nccl
  - numba
  - pip:
    - azureml-sdk[notebooks]
    - mpi4py
    - git+https://github.com/mrocklin/distributed.git@resolve-address-get-cllient
    - git+https://github.com/rapidsai/dask-cuda.git